### ISSUE TITLE
upgrade packages version

### ISSUE THREAD

**Issue by seymourpoler** [pablocom/PersonalSite.Backend#9]
As this screenshot shows
![image](https://user-images.githubusercontent.com/946086/144079915-dadd9c74-255f-4a71-88ad-ad627b21ba70.png)

**Comment by pablocom** [comment]
Is this issue duplicated with https://github.com/pablocom/PersonalSite.Backend/issues/10?

**Comment by seymourpoler** [comment]
Well, one thing is update packages in the solution and another thing is setting up the same version of packages over the solution
